[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mupyjs"
version = "0.0.0"
dependencies = [ "libcst", ]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["mupyjs"] 